Trying to get the deploy to work

diff --git a/pipeline/deployspec.yml b/pipeline/deployspec.yml
--- a/pipeline/deployspec.yml
+++ b/pipeline/deployspec.yml
@@ -13,7 +13,6 @@ phases:
     runtime-versions:
       golang: 1.15
     commands:
-     # update
       - apt-get update -y
       - apt-get install -y ansible
       - wget https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip
@@ -31,15 +30,14 @@ phases:
       - terraform init -no-color
       - AMI=$(terraform output instance_ami | tr -d "\"")
       - echo "AMI: $AMI"
-      - |
-        if [ -z "$AMI" ]; then
-           echo "ERROR: cannot determine instance AMI"
-           exit 1
-        fi
-      - terraform apply -auto-approve -no-color -var instance_ami="$AMI" --target=local_file.inventory --target=local_file.tfvars
-      - cd ansible
-      - ansible-playbook undeploy-backend.yml
-
+      #- |
+      #  if [ -z "$AMI" ]; then
+      #     echo "ERROR: cannot determine instance AMI"
+      #     exit 1
+      #  fi
+      #- terraform apply -auto-approve -no-color -var instance_ami="$AMI" --target=local_file.inventory --target=local_file.tfvars
+      #- cd ansible
+      #- ansible-playbook undeploy-backend.yml
 
 #  post_build:
 #    commands:
