Trying to get the deploy to work

diff --git a/pipeline/deployspec.yml b/pipeline/deployspec.yml
--- a/pipeline/deployspec.yml
+++ b/pipeline/deployspec.yml
@@ -29,16 +29,14 @@ phases:
       - cd $CODEBUILD_SRC_DIR/terraform-infrastructure/avalon.lib.virginia.edu/staging
       - terraform init -no-color
       - ami=$(terraform output instance_ami | tr -d "\"")
-
-#- echo "AMI: $ami"
-#- |
-#  if [ -z "$AMI" ]; then
-#     echo "ERROR: cannot determine instance AMI"
-#     exit 1
-#  fi
-#- terraform apply -auto-approve -no-color -var instance_ami="$AMI" --target=local_file.inventory --target=local_file.tfvars
-#- cd ansible
-#- ansible-playbook undeploy-backend.yml
+      - |
+        if [ -z "$ami" ]; then
+          echo "ERROR: cannot determine instance AMI" ;
+          exit 1 ;
+        fi
+      - terraform apply -auto-approve -no-color -var instance_ami="$ami" --target=local_file.inventory --target=local_file.tfvars
+      - cd ansible
+      - ansible-playbook undeploy-backend.yml
 
 #  post_build:
 #    commands:
